### ISSUE TITLE
Version 680

### ISSUE THREAD

**Issue by yln** [RetVal/objc-runtime#1]
Thanks for sharing this! :)
Saved me from a lot of headache.

Do you plan to make update this for objc4-680?

https://opensource.apple.com/source/objc4/objc4-680/

**Comment by RetVal** [comment]
Yes, Updated.

**Comment by yln** [comment]
Cool, thanks!

**Comment by RetVal** [comment]
objc-runtime.680 has a bug(static instance not initialized before _objc_init called), please waiting for 10.11.13 open source version.

**Comment by RetVal** [comment]
I fix the bug, but selector table version is not matched on 10.11.3, so the version only can be running on 10.11.2
