### ISSUE TITLE
class_copyIvarList中为什么malloc要使用count+1

### ISSUE THREAD

**Issue by Ponfey** [RetVal/objc-runtime#11]
if ((ivars = cls->data()->ro->ivars)  &&  ivars->count) {
        result = (Ivar *)malloc((ivars->count+1) * sizeof(Ivar));
        
        for (auto& ivar : *ivars) {
            if (!ivar.offset) continue;  // anonymous bitfield
            result[count++] = &ivar;
        }
        result[count] = nil;
    }

这里为什么要使用ivars->count+1，以及后面的result[count] = nil;呢？
直接使用ivars->count不行吗？

**Comment by RetVal** [comment]
1. malloc() get a block of memory which is without initialized to zero.
2. result in the loop may get nothing because of anonymous bitfields.
3. for-loop may have named ivar, so counter will be incremented.
4. result[count] = nil will handle (1), (2), (3), and the code is simple enough.
