### ISSUE TITLE
run debug-objc error

### ISSUE THREAD

**Issue by broccolii** [RetVal/objc-runtime#13]
System: 10.14
Xcode version:  10.0

log:
```
dyld: Symbol not found: _objc_debug_taggedpointer_obfuscator
  Referenced from: /usr/lib/system/libxpc.dylib
  Expected in: /Users/Broccoli/Library/Developer/Xcode/DerivedData/objc-ggxyshopfnvlkucfncktchujxfnx/Build/Products/Debug/libobjc.A.dylib
 in /usr/lib/system/libxpc.dylib
```

**Comment by wmf00032** [comment]
I also encountered the same problem

**Comment by daaiwusheng** [comment]
me too

**Comment by FZiOS** [comment]
Any solutions can resolve it?

**Comment by Hanwp** [comment]
Mark. 

MacOS: 10.14.1
XCode:10.0

`dyld: Symbol not found: _objc_debug_taggedpointer_obfuscator
  Referenced from: /usr/lib/system/libxpc.dylib
  Expected in: /Users/hanwei/Desktop/Runtime Learn/runtime-723/libobjc.A.dylib
 in /usr/lib/system/libxpc.dylib`

**Comment by Hanwp** [comment]
自问自答。
是电脑系统的问题，装了macOS10.13.6，就可以正常DEBUG了。

感谢作者提供可编译的runtime😄

**Comment by RetVal** [comment]
new version of runtime 750 for macOS 10.14.

**Comment by FZiOS** [comment]
The new version code is built successfully.Thanks!

**Comment by idewindy** [comment]
> new version of runtime 750 for macOS 10.14.

我在10.14.1的系统上能编译，但是打断点为啥没效果啊，我把xcode删除再重装都不行，我xcode版本是10.1的

**Comment by idewindy** [comment]
我选择的就是这个debug-objc target，刚才我把objc target也编译了下，再运行debug-objc target，断点就执行了

Zero.D.Saber <notifications@github.com> 于2018年12月10日周一 下午12:27写道：

**Comment by idewindy** [comment]
> @idewindy run `debug-objc` target

我看有模拟器的target，为啥没有相关的文件啊

**Comment by tangyumeng** [comment]
Mac OS Mojave: 10.14.1 
Xcode: 10.1 
Same error: 
dyld: Symbol not found: _objc_debug_taggedpointer_obfuscator
  Referenced from: /usr/lib/system/libxpc.dylib
  Expected in: /Users/yumengtang/Library/Developer/Xcode/DerivedData/objc-hacrsmmlntsetzcporbpgnoppuiy/Build/Products/Debug/libobjc.A.dylib
 in /usr/lib/system/libxpc.dylib
Message from debugger: Terminated due to signal 9
Program ended with exit code: 0

**Comment by tangyumeng** [comment]
> Mac OS Mojave: 10.14.1
> Xcode: 10.1
> Same error:
> dyld: Symbol not found: _objc_debug_taggedpointer_obfuscator
> Referenced from: /usr/lib/system/libxpc.dylib
> Expected in: /Users/yumengtang/Library/Developer/Xcode/DerivedData/objc-hacrsmmlntsetzcporbpgnoppuiy/Build/Products/Debug/libobjc.A.dylib
> in /usr/lib/system/libxpc.dylib
> Message from debugger: Terminated due to signal 9
> Program ended with exit code: 0

I know the reason. 
The objc runtime version is too low. 
Can use the objc-750 version.
https://github.com/ssyzh/objc4-750

**Comment by ChenMengqi** [comment]
> > new version of runtime 750 for macOS 10.14.
> 
> 我在10.14.1的系统上能编译，但是打断点为啥没效果啊，我把xcode删除再重装都不行，我xcode版本是10.1的

新建了一个target，重新设置下 Build Phase->Target Dependencies，选择objc ，断点生效了
