### ISSUE TITLE
OSX10.13.5 Xcode9.2  Compile error

### ISSUE THREAD

**Issue by xzjxylophone** [RetVal/objc-runtime#15]
objc-runtime/include/os/lock_private.h:481:2: Use of undeclared identifier 'os_unfair_lock_assert_owner'

**Comment by xzjxylophone** [comment]
obj-runtime 750 have compile error， but obj-runtim 723 doesn't have.

**Comment by RetVal** [comment]
Objective C runtime is version sensitive, some internal implementations should fit to the specific os. Due to this, runtime may be not compatible with old macOS.

**Comment by RetVal** [comment]
feel free to reopen this issue if you have any questions.
