### ISSUE TITLE
Undefined symbol: _objc_opt_class

### ISSUE THREAD

**Issue by 2005wangliqun** [RetVal/objc-runtime#17]
macosOS Catalina 10.15 (19a582a)版本 objc-My Mac 编译，想得到libobjc.A.dylib 文件
Undefined symbol: _objc_opt_class
请问这个大概什么地方出问题了？

**Comment by ChenMengqi** [comment]
same here..

macOS Catalina 10.15
Undefined symbol: _objc_opt_class

**Comment by roylly** [comment]
same problem

**Comment by roylly** [comment]
chang the deployment target to 10.14 can fix this problem.

**Comment by hughbin** [comment]
> chang the deployment target to 10.14 can fix this problem.

why?

**Comment by 531837586** [comment]
nice

**Comment by RetVal** [comment]
Please upgrade to 756.2, and I add an support for objc_opt_class.
