### ISSUE TITLE
运行错误: dyld: lazy symbol binding failed: Symbol not found: _objc_opt_new

### ISSUE THREAD

**Issue by yumumu** [RetVal/objc-runtime#21]
系统版本：macosOS Catalina 10.15.2 (19C57)
Xcode版本：11.3 (11C29)

是需要更新到 779.1 吗？
 https://opensource.apple.com/tarballs/objc4/objc4-779.1.tar.gz

**Comment by RetVal** [comment]
upgraded to 799.1, please have a try.

**Comment by yumumu** [comment]
> upgraded to 799.1, please have a try.

OK 了，谢谢.
