### ISSUE TITLE
objc源码，680，编译出错 ： 'mach-o/dyld_priv.h' file not found 请求解决

### ISSUE THREAD

**Issue by yunfeiyang27** [RetVal/objc-runtime#5]
我在苹果官方下载的objc源码，680，编译出错 ： 'mach-o/dyld_priv.h' file not found 
下载你的这个工程后，编译正常，请问这个文件从哪里找呢？
另外请问下你的博客是？很想拜读一下

**Comment by RetVal** [comment]
dyld_private is a private header in project named dyld.
