### ISSUE TITLE
demo crash

### ISSUE THREAD

**Issue by ZhengIos** [RetVal/objc-runtime#6]
i download you project and run it,my scheme is debug-objc,and in My Mac，it crashed。the log is  dyld: Symbol not found: __object_getExternalHash
  Referenced from: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  Expected in: /Users/chenpeng/Library/Developer/Xcode/DerivedData/objc-exdgpjmktzxpjsfjdmdwwchlrjuq/Build/Products/Debug/libobjc.A.dylib
 in /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation 。
 i find answear in website.almot said import library in Build Phases->Link Binary with Libraries,and changed the library in Optional Status。i tried,however the crash is still exist.

**Comment by yimingzhang007** [comment]
I'm having the same issue here.

**Comment by RetVal** [comment]
Can you give me some information about your Mac OS X version?
706 should be used over 10.12+.

**Comment by yimingcheung** [comment]
Got it running successfully after upgrading to Sierra, thx!

**Comment by banxi1988** [comment]
我运行的时候也有这个问题.(I have the same issue when running the debug-objc target in my mac ( 10.11.6 ,Xcode 8.2)
@RetVal 可否能帮忙指点一下怎么修正? (if you happen to know how to solve this issue; that will help me a lot, thank you)

**Comment by liuzhiyi1992** [comment]
@banxi1988 over mac10.12 up
