### ISSUE TITLE
Xcode 9 无法运行 debug

### ISSUE THREAD

**Issue by 1oo1** [RetVal/objc-runtime#8]
Xcode 9 下打开项目运行失败。

**Comment by RetVal** [comment]
fixed

**Comment by 1oo1** [comment]
还是报错，无法运行 debug-objc 。新 clone 的。
<img width="622" alt="qq20170929-182629 2x" src="https://user-images.githubusercontent.com/6869135/31012424-50215d54-a544-11e7-9148-7ca599f9740e.png">

**Comment by 1oo1** [comment]
貌似是 OBJC_AVAILABLE 这个宏定义是 5 个参数，使用滴地方都是 4 个
